---
- name: Cleaning up temp file on localhost
  local_action: file path=/tmp/kolla_mariadb_cluster state=absent
  changed_when: False
  check_mode: no
  run_once: True

- name: Creating temp file on localhost
  local_action: copy content='' dest=/tmp/kolla_mariadb_cluster mode=0644
  changed_when: False
  check_mode: no
  run_once: True

- name: Creating mariadb volume
  kolla_docker:
    action: "create_volume"
    common_options: "{{ docker_common_options }}"
    name: "mariadb"
  register: mariadb_volume

- name: Writing hostname of host with existing cluster files to temp file
  local_action: copy content={{ ansible_hostname }} dest=/tmp/kolla_mariadb_cluster mode=0644
  changed_when: False
  check_mode: no
  when: not mariadb_volume | changed

- name: Registering host from temp file
  set_fact:
    has_cluster: "{{ lookup('file', '/tmp/kolla_mariadb_cluster') | length > 0 }}"

- name: Cleaning up temp file on localhost
  local_action: file path=/tmp/kolla_mariadb_cluster state=absent
  changed_when: False
  check_mode: no
  run_once: True
