---
- name: Get container facts
  kolla_container_facts:
    name:
      - panko_api
  register: container_facts

- name: Checking free port for Panko API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ panko_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['panko_api'] is not defined
    - inventory_hostname in groups['panko-api']
