---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    recurse: yes
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ glance_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
  register: glance_config_jsons
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ glance_services }}"
  notify:
    - Restart glance-api container
    - Restart glance-registry container

- name: Copying over glance-*.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/{{ item.key }}.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/database.conf"
      - "{{ node_custom_config }}/messaging.conf"
      - "{{ node_custom_config }}/glance.conf"
      - "{{ node_custom_config }}/glance/{{ item.key }}.conf"
      - "{{ node_custom_config }}/glance/{{ inventory_hostname }}/{{ item.key }}.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ item.key }}.conf"
  register: glance_confs
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ glance_services }}"
  notify:
    - Restart glance-api container
    - Restart glance-registry container

- name: Check if policies shall be overwritten
  local_action: stat path="{{ node_custom_config }}/glance/policy.json"
  run_once: True
  register: glance_policy

- name: Copying over glance-swift.conf for glance_api
  vars:
    glance_api: "{{ glance_services['glance-api'] }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/glance-swift.conf.j2"
      - "{{ node_custom_config }}/glance-swift.conf"
      - "{{ node_custom_config }}/glance/glance-swift.conf"
      - "{{ node_custom_config }}/glance/{{ inventory_hostname }}/glance-swift.conf"
    dest: "{{ node_config_directory }}/glance-api/glance-swift.conf"
  register: glance_swift_conf
  when:
    - glance_api.enabled | bool
    - inventory_hostname in groups[glance_api.group]
    - glance_backend_swift | bool
  notify:
    - Restart glance-api container

- name: Copying over existing policy.json
  template:
    src: "{{ node_custom_config }}/glance/policy.json"
    dest: "{{ node_config_directory }}/{{ item.key }}/policy.json"
  register: glance_policy_jsons
  when:
    - glance_policy.stat.exists
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ glance_services }}"
  notify:
    - Restart glance-api container
    - Restart glance-registry container

- name: Check glance containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
  register: check_glance_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ glance_services }}"
  notify:
    - Restart glance-api container
    - Restart glance-registry container
