---
- name: Keystone sanity checks
  kolla_toolbox:
    module_name: os_auth
    module_args:
      auth: "{{ openstack_keystone_auth }}"
  run_once: True
  delegate_to: "{{ groups['keystone'][0] }}"
  when: kolla_enable_sanity_keystone | bool
