---
- name: Restart vmtp container
  vars:
    service_name: "vmtp"
    service: "{{ vmtp_services[service_name] }}"
    vmtp_container: "{{ check_vmtp_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes|reject('equalto', '')|list }}"
  when:
    - action != "config"
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - vmtp_confs.changed | bool
      or vmtp_container.changed | bool
