---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    recurse: yes
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ tempest_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
  register: tempest_config_jsons
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ tempest_services }}"
  notify:
    - Restart tempest container

- name: Copying over tempest.conf
  vars:
    project_name: "tempest"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/tempest.conf.j2"
      - "{{ node_custom_config }}/tempest.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/tempest.conf"
  register: tempest_confs
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ tempest_services }}"
  notify:
    - Restart tempest container

- name: Check tempest containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
  register: check_tempest_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ tempest_services }}"
  notify:
    - Restart tempest container
