---
- name: Checking gnocchi backend for ceilometer
  run_once: True
  local_action: fail msg="gnocchi is required but not enabled"
  changed_when: false
  when:
    - enable_ceilometer | bool
    - not enable_gnocchi | bool
