---
- include: config.yml

- include: bootstrap_service.yml

# TODO(jeffrey4l): ceilometer-api and ceilometer-collector are marked as
# deprecated and will be removed already. Upgrade to Pike should remove
# ceilometer-api and ceilometer-collector container. This task should be
# remove in Q cycle.
- name: Containers are being removed
  kolla_docker:
    name: "{{ item }}"
    action: remove_container
  with_items:
    - ceilometer_api
    - ceilometer_collector

- name: Flush handlers
  meta: flush_handlers
