---
- name: Get container facts
  kolla_container_facts:
    name:
      - grafana
  register: container_facts

- name: Checking free port for Grafana server
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ grafana_server_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['grafana'] is not defined
    - inventory_hostname in groups['grafana']
