---
- name: Get container facts
  kolla_container_facts:
    name:
      - openvswitch_db
  register: container_facts

- name: Checking free port for OVSDB
  vars:
    openvswitch_db: "{{ openvswitch_services['openvswitch-db-server'] }}"
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ ovsdb_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['openvswitch_db'] is not defined
    - inventory_hostname in groups[openvswitch_db.group]
    - openvswitch_db.enabled | bool
