---
- name: Get container facts
  kolla_container_facts:
    name:
      - magnum_api
  register: container_facts

- name: Checking free port for Magnum API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ magnum_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['magnum_api'] is not defined
    - inventory_hostname in groups['magnum-api']
