---
- name: Get container facts
  kolla_container_facts:
    name:
      - aodh_api
  register: container_facts

- name: Checking free port for Aodh API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ aodh_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['aodh_api'] is not defined
    - inventory_hostname in groups['aodh-api']
