---
- name: Cinder sanity check - create volume
  kolla_toolbox:
    module_name: os_volume
    module_args:
      auth: "{{ openstack_cinder_auth }}"
      state: present
      size: 1
      display_name: kolla_test_volume
  run_once: True
  delegate_to: "{{ groups['cinder-api'][0] }}"
  when: kolla_enable_sanity_cinder | bool

- name: Cinder sanity check - cleanup volume
  kolla_toolbox:
    module_name: os_volume
    module_args:
      auth: "{{ openstack_cinder_auth }}"
      state: absent
      display_name: kolla_test_volume
  run_once: True
  delegate_to: "{{ groups['cinder-api'][0] }}"
  when: kolla_enable_sanity_cinder | bool
