---
project_name: "iscsi"

####################
# Docker
####################
iscsi_install_type: "{{ kolla_install_type }}"
iscsi_tag: "{{ openstack_release }}"

iscsid_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ iscsi_install_type }}-iscsid"
iscsid_tag: "{{ iscsi_tag }}"
iscsid_image_full: "{{ iscsid_image }}:{{ iscsid_tag }}"

tgtd_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ iscsi_install_type }}-tgtd"
tgtd_tag: "{{ iscsi_tag }}"
tgtd_image_full: "{{ tgtd_image }}:{{ tgtd_tag }}"
