---
- name: Get container facts
  kolla_container_facts:
    name:
      - gnocchi_api
  register: container_facts

- name: Checking free port for Gnocchi API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ gnocchi_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['gnocchi_api'] is not defined
    - inventory_hostname in groups['gnocchi-api']
