---
project_name: "tacker"

tacker_services:
  tacker-server:
    container_name: "tacker_server"
    group: "tacker-server"
    enabled: true
    image: "{{ tacker_server_image_full }}"
    volumes:
      - "{{ node_config_directory }}/tacker-server/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  tacker-conductor:
    container_name: "tacker_conductor"
    group: "tacker-conductor"
    enabled: true
    image: "{{ tacker_conductor_image_full }}"
    volumes:
      - "{{ node_config_directory }}/tacker-conductor/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"

####################
# Database
####################
tacker_database_name: "tacker"
tacker_database_user: "tacker"
tacker_database_address: "{{ kolla_internal_fqdn }}:{{ database_port }}"

########
# Docker
########
tacker_install_type: "{{ kolla_install_type }}"
tacker_tag: "{{ openstack_release }}"

tacker_server_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ tacker_install_type }}-tacker-server"
tacker_server_tag: "{{ tacker_tag }}"
tacker_server_image_full: "{{ tacker_server_image }}:{{ tacker_server_tag }}"

tacker_conductor_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ tacker_install_type }}-tacker-conductor"
tacker_conductor_tag: "{{ tacker_tag }}"
tacker_conductor_image_full: "{{ tacker_conductor_image }}:{{ tacker_conductor_tag }}"

####################
# OpenStack
####################
tacker_admin_endpoint: "{{ admin_protocol }}://{{ kolla_internal_fqdn }}:{{ tacker_server_port }}"
tacker_internal_endpoint: "{{ internal_protocol }}://{{ kolla_internal_fqdn }}:{{ tacker_server_port }}"
tacker_public_endpoint: "{{ public_protocol }}://{{ kolla_external_fqdn }}:{{ tacker_server_port }}"

tacker_logging_debug: "{{ openstack_logging_debug }}"

tacker_keystone_user: "tacker"

openstack_tacker_auth: "{{ openstack_auth }}"
