---
- include: register.yml
  when: inventory_hostname in groups['tacker-server']

- include: config.yml
  when: inventory_hostname in groups['tacker-server'] or
        inventory_hostname in groups['tacker-conductor']

- include: bootstrap.yml
  when: inventory_hostname in groups['tacker-server']

- name: Flush handlers
  meta: flush_handlers
