---
- name: Get container facts
  kolla_container_facts:
    name:
      - qdrouterd
  register: container_facts

- name: Checking free port for Qdrouterd
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ qdrouterd_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['qdrouterd'] is not defined
    - inventory_hostname in groups['qdrouterd']

- name: Check if all qdrouterd hostnames are resolvable
  command: "getent ahostsv4 {{ hostvars[item]['ansible_hostname'] }}"
  changed_when: false
  register: qdrouterd_hostnames
  with_items: "{{ groups['qdrouterd'] }}"

- fail: msg="Hostname has to resolve to IP address of api_interface"
  with_items: "{{ qdrouterd_hostnames.results }}"
  when:
    - "item.stdout.find(hostvars[item['item']]['ansible_' ~ hostvars[item['item']]['api_interface']]['ipv4']['address']) == -1"
