---
project_name: "mariadb"

mariadb_services:
  mariadb:
    container_name: mariadb
    group: mariadb
    enabled: true
    image: "{{ mariadb_image_full }}"
    volumes:
      - "{{ node_config_directory }}/mariadb/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "mariadb:/var/lib/mysql"
      - "kolla_logs:/var/log/kolla/"


####################
# Database
####################
database_cluster_name: "openstack"
database_max_timeout: 60

####################
# Docker
####################
mariadb_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-mariadb"
mariadb_tag: "{{ openstack_release }}"
mariadb_image_full: "{{ mariadb_image }}:{{ mariadb_tag }}"
