---
project_name: "haproxy"

haproxy_services:
  haproxy:
    container_name: haproxy
    group: haproxy
    enabled: true
    image: "{{ haproxy_image_full }}"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/haproxy/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "haproxy_socket:/var/lib/kolla/haproxy/"
  keepalived:
    container_name: keepalived
    group: haproxy
    enabled: true
    image: "{{ keepalived_image_full }}"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/keepalived/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/lib/modules:/lib/modules:ro"
      - "haproxy_socket:/var/lib/kolla/haproxy/"


####################
# Docker
####################
keepalived_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-keepalived"
keepalived_tag: "{{ openstack_release }}"
keepalived_image_full: "{{ keepalived_image }}:{{ keepalived_tag }}"

haproxy_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-haproxy"
haproxy_tag: "{{ openstack_release }}"
haproxy_image_full: "{{ haproxy_image }}:{{ haproxy_tag }}"

haproxy_client_timeout: "1m"
haproxy_server_timeout: "1m"

haproxy_glance_api_client_timeout: "6h"
haproxy_glance_api_server_timeout: "6h"
