---
- name: Get container facts
  kolla_container_facts:
    name:
      - zun_api
  register: container_facts

- name: Checking free port for Zun API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ zun_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['zun_api'] is not defined
    - inventory_hostname in groups['zun-api']
