---
project_name: "rabbitmq"

rabbitmq_services:
  rabbitmq:
    container_name: "{{ project_name }}"
    group: "{{ role_rabbitmq_groups }}"
    enabled: true
    image: "{{ rabbitmq_image_full }}"
    environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
      RABBITMQ_CLUSTER_COOKIE: "{{ role_rabbitmq_cluster_cookie }}"
      RABBITMQ_LOG_DIR: "/var/log/kolla/{{ project_name }}"
    volumes:
      - "{{ node_config_directory }}/{{ project_name }}/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ project_name }}:/var/lib/rabbitmq/"
      - "kolla_logs:/var/log/kolla/"


####################
# Docker
####################
rabbitmq_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-rabbitmq"
rabbitmq_tag: "{{ openstack_release }}"
rabbitmq_image_full: "{{ rabbitmq_image }}:{{ rabbitmq_tag }}"


####################
# Message-Broker
####################
rabbitmq_user: "openstack"
rabbitmq_cluster_name: "openstack"
rabbitmq_hostname: "{{ ansible_hostname }}"
