---
- name: Destroying Kolla host configuration
  command: >
    env enable_haproxy={{ enable_haproxy }}
        enable_swift={{ enable_swift }}
        glance_file_datadir_volume={{ glance_file_datadir_volume }}
        kolla_internal_vip_address={{ kolla_internal_vip_address }}
        kolla_external_vip_address={{ kolla_external_vip_address }}
        kolla_dev_repos_directory={{ kolla_dev_repos_directory }}
        destroy_include_dev={{ destroy_include_dev }}
        /tmp/kolla-cleanup/tools/cleanup-host

- name: Destroying kolla-cleanup folder
  file:
    path: /tmp/kolla-cleanup
    state: absent
