---
- name: Get container facts
  kolla_container_facts:
    name:
      - sahara_api
  register: container_facts

- name: Checking free port for Sahara API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ sahara_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['sahara_api'] is not defined
    - inventory_hostname in groups['sahara-api']
