---
- name: Get container facts
  kolla_container_facts:
    name:
      - mistral_api
  register: container_facts

- name: Checking free port for Mistral API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ mistral_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['mistral_api'] is not defined
    - inventory_hostname in groups['mistral-api']
