---
- name: Restart nova-compute
  win_service:
    name: nova-compute
    state: restarted

- name: Restart neutron-hyperv-agent
  win_service:
    name: neutron-hyperv-agent
    state: restarted

- name: Restart FreeRDP-WebConnect
  win_service:
    name: wsgate
    state: restarted
